<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.1.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'key1',
  'author' => 'karamat',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Practice',
  'published_date' => '2017-08-16 04:37:18',
  'type' => 'module',
  'version' => 1502858238,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Practice',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'key1_Course_Management',
      'class' => 'key1_Course_Management',
      'path' => 'modules/key1_Course_Management/key1_Course_Management.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'key1_student_management',
      'class' => 'key1_student_management',
      'path' => 'modules/key1_student_management/key1_student_management.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/key1_course_management_key1_student_management_key1_student_management.php',
      'to_module' => 'key1_student_management',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/key1_course_management_key1_student_management_key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/key1_course_management_key1_student_managementMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/key1_Course_Management',
      'to' => 'modules/key1_Course_Management',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/key1_student_management',
      'to' => 'modules/key1_student_management',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ko_KR',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'lv_LV',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'nb_NO',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'nl_NL',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'pl_PL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'pt_PT',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ro_RO',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ru_RU',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'sv_SE',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'tr_TR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'zh_TW',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'zh_CN',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'pt_BR',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ca_ES',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'en_UK',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'sr_RS',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'sk_SK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'sq_AL',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'et_EE',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'es_LA',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'fi_FI',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'ar_SA',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_student_management.php',
      'to_module' => 'key1_student_management',
      'language' => 'uk_UA',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'bg_BG',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'cs_CZ',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'da_DK',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'de_DE',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'el_EL',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'es_ES',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'fr_FR',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'he_IL',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'hu_HU',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'it_it',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'lt_LT',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ja_JP',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ko_KR',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'lv_LV',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'nb_NO',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'nl_NL',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'pl_PL',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'pt_PT',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ro_RO',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ru_RU',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'sv_SE',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'tr_TR',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'zh_TW',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'zh_CN',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'pt_BR',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ca_ES',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'en_UK',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'sr_RS',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'sk_SK',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'sq_AL',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'et_EE',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'es_LA',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'fi_FI',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'ar_SA',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
      'language' => 'uk_UA',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'sidecar' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/key1_course_management_key1_student_management_key1_student_management.php',
      'to_module' => 'key1_student_management',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/key1_course_management_key1_student_management_key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/key1_course_management_key1_student_management_key1_student_management.php',
      'to_module' => 'key1_student_management',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/key1_course_management_key1_student_management_key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/key1_course_management_key1_student_management_key1_student_management.php',
      'to_module' => 'key1_student_management',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/key1_course_management_key1_student_management_key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/key1_course_management_key1_student_management_key1_student_management.php',
      'to_module' => 'key1_student_management',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/key1_course_management_key1_student_management_key1_Course_Management.php',
      'to_module' => 'key1_Course_Management',
    ),
  ),
);